---
# roles/timesync/tasks/main.yml

- name: Ensure systemd-timesyncd is installed
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: present

- name: Ensure systemd-timesyncd is started and enabled
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: Time | Set configuration file for systemd-timesyncd
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^NTP='
    line: "NTP={{ timesync_time_server }}"
    create: true
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  notify: Restart timesyncd
